project:
  type: website

website:
  title: "Température Lac"
  navbar:
    left:
      - href: index.qmd
        text: Hermance
      - about.qmd

format:
  html:
    page-layout: custom
    theme: yeti
    css: "css/styles.css"
echo: false

